// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"leagueapi.com.br/rest/models"
)

// LiveMatchOKCode is the HTTP code returned for type LiveMatchOK
const LiveMatchOKCode int = 200

/*LiveMatchOK get live league match

swagger:response liveMatchOK
*/
type LiveMatchOK struct {
}

// NewLiveMatchOK creates LiveMatchOK with default headers values
func NewLiveMatchOK() *LiveMatchOK {

	return &LiveMatchOK{}
}

// WriteResponse to the client
func (o *LiveMatchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*LiveMatchDefault generic error response

swagger:response liveMatchDefault
*/
type LiveMatchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewLiveMatchDefault creates LiveMatchDefault with default headers values
func NewLiveMatchDefault(code int) *LiveMatchDefault {
	if code <= 0 {
		code = 500
	}

	return &LiveMatchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the live match default response
func (o *LiveMatchDefault) WithStatusCode(code int) *LiveMatchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the live match default response
func (o *LiveMatchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the live match default response
func (o *LiveMatchDefault) WithPayload(payload *models.Error) *LiveMatchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the live match default response
func (o *LiveMatchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LiveMatchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
