// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LiveMatchHandlerFunc turns a function with the right signature into a live match handler
type LiveMatchHandlerFunc func(LiveMatchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LiveMatchHandlerFunc) Handle(params LiveMatchParams) middleware.Responder {
	return fn(params)
}

// LiveMatchHandler interface for that can handle valid live match params
type LiveMatchHandler interface {
	Handle(LiveMatchParams) middleware.Responder
}

// NewLiveMatch creates a new http.Handler for the live match operation
func NewLiveMatch(ctx *middleware.Context, handler LiveMatchHandler) *LiveMatch {
	return &LiveMatch{Context: ctx, Handler: handler}
}

/*LiveMatch swagger:route GET / api liveMatch

LiveMatch live match API

*/
type LiveMatch struct {
	Context *middleware.Context
	Handler LiveMatchHandler
}

func (o *LiveMatch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLiveMatchParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
