// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"leagueapi.com.br/rest/models"
)

// AuthOKCode is the HTTP code returned for type AuthOK
const AuthOKCode int = 200

/*AuthOK login into system

swagger:response authOK
*/
type AuthOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewAuthOK creates AuthOK with default headers values
func NewAuthOK() *AuthOK {

	return &AuthOK{}
}

// WithPayload adds the payload to the auth o k response
func (o *AuthOK) WithPayload(payload []*models.User) *AuthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth o k response
func (o *AuthOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*AuthDefault generic error response

swagger:response authDefault
*/
type AuthDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAuthDefault creates AuthDefault with default headers values
func NewAuthDefault(code int) *AuthDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auth default response
func (o *AuthDefault) WithStatusCode(code int) *AuthDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auth default response
func (o *AuthDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the auth default response
func (o *AuthDefault) WithPayload(payload *models.Error) *AuthDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth default response
func (o *AuthDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
