// Code generated by go-swagger; DO NOT EDIT.

package live

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewLiveParams creates a new LiveParams object
// no default values defined in spec.
func NewLiveParams() LiveParams {

	return LiveParams{}
}

// LiveParams contains all the bound params for the live operation
// typically these are obtained from a http.Request
//
// swagger:parameters live
type LiveParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewLiveParams() beforehand.
func (o *LiveParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
