// Code generated by go-swagger; DO NOT EDIT.

package live

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LiveHandlerFunc turns a function with the right signature into a live handler
type LiveHandlerFunc func(LiveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LiveHandlerFunc) Handle(params LiveParams) middleware.Responder {
	return fn(params)
}

// LiveHandler interface for that can handle valid live params
type LiveHandler interface {
	Handle(LiveParams) middleware.Responder
}

// NewLive creates a new http.Handler for the live operation
func NewLive(ctx *middleware.Context, handler LiveHandler) *Live {
	return &Live{Context: ctx, Handler: handler}
}

/*Live swagger:route GET /live live live

Live live API

*/
type Live struct {
	Context *middleware.Context
	Handler LiveHandler
}

func (o *Live) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLiveParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
