// Code generated by go-swagger; DO NOT EDIT.

package live

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"leagueapi.com.br/rest/models"
)

// LiveOKCode is the HTTP code returned for type LiveOK
const LiveOKCode int = 200

/*LiveOK connect to websocket

swagger:response liveOK
*/
type LiveOK struct {
}

// NewLiveOK creates LiveOK with default headers values
func NewLiveOK() *LiveOK {

	return &LiveOK{}
}

// WriteResponse to the client
func (o *LiveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*LiveDefault generic error response

swagger:response liveDefault
*/
type LiveDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewLiveDefault creates LiveDefault with default headers values
func NewLiveDefault(code int) *LiveDefault {
	if code <= 0 {
		code = 500
	}

	return &LiveDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the live default response
func (o *LiveDefault) WithStatusCode(code int) *LiveDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the live default response
func (o *LiveDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the live default response
func (o *LiveDefault) WithPayload(payload *models.Error) *LiveDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the live default response
func (o *LiveDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LiveDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
